import { readFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { join } from 'node:path';
import { MODEL, MODEL_DIRECTORY, MODEL_FILES, MODEL_ROOT } from './model-config.mjs';

export const modelInfo = Object.freeze({ ...MODEL, id: MODEL.source, offline: true, local: true });

let instance;
let state = 'unloaded';
let failure;
let loadedAt;

export function getModelStatus() {
  return {
    mode: 'local-model', state, local: true, offline: true,
    ...modelInfo, loadedAt: loadedAt ?? null,
    evidence: 'evidence/model-spike.json (generated by npm run verify:model)',
    ...(failure ? { error: failure } : {}),
  };
}

/** Verify local artifacts before native inference. This function never downloads. */
export async function verifyLocalModelFiles() {
  let manifest;
  try {
    manifest = JSON.parse(await readFile(join(MODEL_DIRECTORY, 'manifest.json'), 'utf8'));
  } catch {
    throw new Error('Local model is not installed. Run npm run setup:model, then start again.');
  }
  if (manifest.repository !== MODEL.repository || manifest.revision !== MODEL.revision) {
    throw new Error('Local model revision does not match this prototype. Run npm run setup:model.');
  }
  for (const file of MODEL_FILES) {
    const expected = manifest.files?.[file];
    if (!expected?.sha256 || !Number.isSafeInteger(expected.bytes)) {
      throw new Error(`Model manifest is missing ${file}. Run npm run setup:model.`);
    }
    const data = await readFile(join(MODEL_DIRECTORY, file));
    const hash = createHash('sha256').update(data).digest('hex');
    if (data.length !== expected.bytes || hash !== expected.sha256) {
      throw new Error(`Model integrity check failed for ${file}. Run npm run setup:model.`);
    }
    if (file === 'onnx/model_quantized.onnx' &&
        (hash !== MODEL.weightsSha256 || data.length !== MODEL.weightsBytes)) {
      throw new Error('Model weights differ from the pinned upstream checksum.');
    }
  }
  return manifest;
}

/** Load a CPU-only local pipeline. Failure is explicit; there is no lexical fallback. */
export async function loadModel() {
  if (!instance) {
    state = 'loading';
    instance = (async () => {
      await verifyLocalModelFiles();
      const { pipeline, env } = await import('@huggingface/transformers');
      env.allowRemoteModels = false;
      env.allowLocalModels = true;
      env.useFSCache = false;
      env.localModelPath = MODEL_ROOT;
      const extractor = await pipeline('feature-extraction', MODEL.localName, {
        dtype: MODEL.dtype,
        device: 'cpu',
        local_files_only: true,
        session_options: { intraOpNumThreads: 2, interOpNumThreads: 1 },
      });
      // The feature-extraction pipeline forwards truncation but not max_length.
      // Set the public tokenizer config so its default matches the source card's
      // 256-word-piece recommendation instead of the export's generic BERT 512.
      extractor.tokenizer.config.model_max_length = MODEL.maxTokens;
      state = 'ready';
      loadedAt = new Date().toISOString();
      failure = undefined;
      return extractor;
    })().catch((error) => {
      state = 'error';
      failure = error.message;
      instance = undefined;
      throw error;
    });
  }
  return instance;
}

/** Return normalized mean-pooled embeddings. Inputs remain in this Node process. */
export async function embed(texts) {
  const list = typeof texts === 'string' ? [texts] : texts;
  if (!Array.isArray(list) || list.length < 1 || list.length > 128 ||
      list.some((text) => typeof text !== 'string' || !text.trim() || text.length > 2000)) {
    throw new TypeError('Embed expects 1–128 non-empty strings of at most 2000 characters.');
  }
  const extractor = await loadModel();
  const result = await extractor(list, {
    pooling: 'mean', normalize: true,
  });
  const rows = result.tolist();
  if (rows.length !== list.length || rows.some((row) =>
    row.length !== MODEL.dimensions || row.some((value) => !Number.isFinite(value)))) {
    throw new Error('Model returned an invalid embedding shape or value.');
  }
  return rows;
}

export function cosineSimilarity(a, b) {
  if (!Array.isArray(a) || !Array.isArray(b) || a.length === 0 || a.length !== b.length) {
    throw new TypeError('Cosine similarity needs vectors of equal nonzero length.');
  }
  let dot = 0; let normA = 0; let normB = 0;
  for (let i = 0; i < a.length; i += 1) {
    if (!Number.isFinite(a[i]) || !Number.isFinite(b[i])) {
      throw new TypeError('Cosine similarity needs finite numeric vectors.');
    }
    dot += a[i] * b[i]; normA += a[i] ** 2; normB += b[i] ** 2;
  }
  if (normA === 0 || normB === 0) throw new TypeError('Cosine similarity is undefined for zero vectors.');
  return Math.max(-1, Math.min(1, dot / Math.sqrt(normA * normB)));
}

// Cache only curated activity embeddings, never free-text user queries.
let cachedCorpusKey;
let cachedCorpusEmbeddings;

/** Rank [{ id, semanticText }] by cosine similarity; scores are not probabilities. */
export async function rank(query, candidates) {
  if (typeof query !== 'string' || !query.trim() || query.length > 2000) {
    throw new TypeError('Rank expects a non-empty query string of at most 2000 characters.');
  }
  if (!Array.isArray(candidates) || candidates.length > 128 || candidates.some((item) =>
    !item || typeof item.id !== 'string' || typeof item.semanticText !== 'string')) {
    throw new TypeError('Rank expects up to 128 candidates with id and semanticText strings.');
  }
  if (!candidates.length) return [];
  const corpusKey = JSON.stringify(candidates);
  let corpusEmbeddings;
  if (cachedCorpusKey === corpusKey) corpusEmbeddings = cachedCorpusEmbeddings;
  else {
    corpusEmbeddings = await embed(candidates.map((item) => item.semanticText));
    cachedCorpusKey = corpusKey;
    cachedCorpusEmbeddings = corpusEmbeddings;
  }
  const [queryEmbedding] = await embed(query);
  return candidates.map((candidate, index) => ({
    id: candidate.id, score: cosineSimilarity(queryEmbedding, corpusEmbeddings[index]),
  })).sort((a, b) => b.score - a.score || a.id.localeCompare(b.id));
}
